<?php

namespace _\lot\x {
    function excerpt($content) {
        // `excerpt` data has been set
        if ($content) {
            return $content; // Return the initial value
        }
        $content = $this->content;
        $cut = \State::get('x.excerpt.cut');
        // Excerpt cropper does not exist, return the page’s `description`
        if (!$content || !$cut || false === \strpos($content, $cut)) {
            // If page’s `description` is empty, create a fake excerpt generated by the page’s `content`
            return $this->description ?? \To::excerpt((string) $content);
        }
        // Return the first part!
        $content = \trim(\explode($cut, $content)[0]);
        return "" !== $content ? $content : null;
    }
    \Hook::set('page.excerpt', __NAMESPACE__ . "\\excerpt", 2.1);
}

namespace _\lot\x\excerpt {
    function anchor($content) {
        $state = \State::get('x.excerpt', true);
        $cut = $state['cut'];
        $anchor = $state['anchor'][0];
        if (empty($cut) || \State::is('pages') || false === \strpos($content, $cut)) {
            return $content;
        }
        return \implode('<span class="fi" id="' . \sprintf($anchor, $this->id) . '"></span>', \explode($cut, $content, 2));
    }
    \Hook::set('page.content', __NAMESPACE__ . "\\anchor", 2.1);
}
