<?php

namespace x {
    function excerpt($excerpt) {
        // `excerpt` data has been set
        if ($excerpt) {
            return $excerpt; // Return the initial value
        }
        extract($GLOBALS, \EXTR_SKIP);
        $content = $this->content;
        $cut = $state->x->excerpt->cut ?? "";
        // Excerpt cropper does not exist, return the page’s `description`
        if (!$content || !$cut || false === \strpos($content, $cut)) {
            // If page’s `description` is empty, create a fake excerpt generated by the page’s `content`
            return $this->description ?? \To::description((string) $content);
        }
        // Return the first part!
        $content = \trim(\explode($cut, $content)[0]);
        return "" !== $content ? $content : null;
    }
    \Hook::set('page.excerpt', __NAMESPACE__ . "\\excerpt", 2.1);
}

namespace x\excerpt {
    function anchor($content) {
        if (!$content) {
            return $content;
        }
        extract($GLOBALS, \EXTR_SKIP);
        if ($state->is('pages')) {
            return $content;
        }
        $cut = $state->x->excerpt->cut ?? "";
        $anchor = $state->x->excerpt->anchor[0] ?? "";
        if (!$cut || false === \strpos($content, $cut)) {
            return $content;
        }
        return \implode('<span class="fi" id="' . \sprintf($anchor, $this->id) . '"></span>', \explode($cut, $content, 2));
    }
    \Hook::set('page.content', __NAMESPACE__ . "\\anchor", 2.1);
}